#!/bin/bash
#SBATCH --job-name=samtools_merge
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --time=16:00:00     
#SBATCH --output=slurm_out/%x.o%j
#SBATCH --error=slurm_out/%x.e%j

##USAGE: export INDIR=''; sbatch --mail-user=$EMAIL /depot/jwisecav/data/ceratopteris/github/ceratopteris_bsa_by_rnaseq/snp_calling/4_2_run_mergeBAMsamples.sub

###INDIR should be the path to the input directory

echo $INDIR

echo 'cd $INDIR'
cd $INDIR

echo 'module load samtools'
module load samtools

echo 'samtools merge merged_samples_only.bam her19Ma_ReadGroups.bam her19He_ReadGroups.bam her14Ma_ReadGroups.bam her14He_ReadGroups.bam her13Ma_ReadGroups.bam her13He_ReadGroups.bam'

samtools merge merged_samples_only.bam her19Ma_ReadGroups.bam her19He_ReadGroups.bam her14Ma_ReadGroups.bam her14He_ReadGroups.bam her13Ma_ReadGroups.bam her13He_ReadGroups.bam

echo 'samtools index merged_samples_only.bam'

samtools index merged_samples_only.bam