#!/bin/bash
#SBATCH --job-name=GATK_HaplotypeCaller
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --time=24:00:00     
#SBATCH --output=../../slurm_out/%x.o%j
#SBATCH --error=../../slurm_out/%x.e%j

##USAGE: export SAMPLE=''; export INDIR=''; export OUTDIR=''; sbatch --mail-user=$EMAIL /depot/jwisecav/data/ceratopteris/github/ceratopteris_bsa_by_rnaseq/snp_calling/5_1_run_HaplotypeCaller_GATK_format.sub

###INDIR should be the path to the full directory containing the read groups bam file 
###OUTDIR should be full path to the output directory

echo $INDIR
echo $OUTDIR
echo $SAMPLE

echo 'cd $OUTDIR'
cd $OUTDIR

echo 'module load biocontainers/default'
echo 'module load gatk4/4.2.6.1'

#load modules
module load biocontainers/default
module load gatk4/4.2.6.1

echo 'gatk HaplotypeCaller -I '$INDIR/${SAMPLE}_ReadGroups.bam' -O ${SAMPLE}_HaplotypeCaller.g.vcf.gz -R '/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/01_genome_reference/Crichardii_676_v2.0.fa''

#call variants in the data 
gatk HaplotypeCaller -I '$INDIR/${SAMPLE}_ReadGroups.bam' -O ${SAMPLE}_HaplotypeCaller.g.vcf.gz -R '/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/01_genome_reference/Crichardii_676_v2.0.fa' 