#!/bin/bash
#SBATCH --job-name=SnpSift_RD
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=2:00:00     
#SBATCH --output=../Slurm-out/%x.o%j
#SBATCH --error=../Slurm-out/%x.e%j


##USAGE: export SAMPLE=''; sbatch --mail-user=$EMAIL /depot/jwisecav/data/ceratopteris/github/ceratopteris_bsa_by_rnaseq/snp_calling/run_snpsift_filtering_no_ss_removal.sub

echo $SAMPLE

#load module 
echo 'module load biocontainers/default'
echo 'module load snpsift'
module load biocontainers/default
module load snpsift


#Filter to retain only snps present on both forward and reverse strands 
echo 'cat /depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/04_snp_calling/05_VariantFiltering/sample_snps_filtered/${SAMPLE}_chr_intersect.vcf | SnpSift filter "(( DP4[2] >= 2 ) & ( DP4[3] >= 2 ))" >  /scratch/bell/kburow/BSA_non_homozygous/${SAMPLE}_chr_int_strand_filter.vcf'
cat /depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/04_snp_calling/05_VariantFiltering/sample_snps_filtered/${SAMPLE}_chr_intersect.vcf | SnpSift filter "(( DP4[2] >= 2 ) & ( DP4[3] >= 2 ))" >  /scratch/bell/kburow/BSA_non_homozygous/${SAMPLE}_chr_int_strand_filter.vcf

#Filter to remove indels and for quality
cat /scratch/bell/kburow/BSA_non_homozygous/${SAMPLE}_chr_int_strand_filter.vcf | SnpSift filter "((QUAL >= 30) & !(exists INDEL))" > /scratch/bell/kburow/BSA_non_homozygous/${SAMPLE}_chr_int_strand_qual_indel_filtered.vcf