#!/bin/bash
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=120G
#SBATCH --time=20:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# usage: export SAMPLE='sampleid'; export INDEXPATH='03_kallisto/Crichardii_676_v2.1.transcript.fa.kallisto.index'; sbatch --mail-user=$EMAIL -J "${SAMPLE}-kallisto" ../../github/ceratopteris_bsa_by_rnaseq/rnaseq_analysis/3_run_kallisto_paired_dry_spores.sub

module use /depot/jwisecav/apps/modulefiles 
module load conda-env/kallisto-py3.8.3      

#User defined parameters
INDIR='dry_spores'
OUTDIR='03_kallisto'

#Create output directory
echo "mkdir ${OUTDIR}/${SAMPLE}/"
mkdir ${OUTDIR}/${SAMPLE}/

#Kallisto command:
kallisto quant -t 24 -i $INDEXPATH -o ${OUTDIR}/${SAMPLE}/ ${INDIR}/${SAMPLE}_1.fq.gz ${INDIR}/${SAMPLE}_2.fq.gz

