#!/bin/bash
#SBATCH --job-name=STARindex
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=90G
#SBATCH --time=48:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# USAGE: export OUTDIR='/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/03_rnaseq_analysis/04_transcript_mapping/'; export GENOMEFASTA='/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/01_genome_reference/Crichardii_676_v2.0.fa'; export ANNOTFILE='/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/01_genome_reference/Crichardii_676_v2.1.gene_exons.gff3'; sbatch --mail-user=$EMAIL ../../github/ceratopteris_bsa_by_rnaseq/rnaseq_analysis/4_run_STAR_index.sub 

###OUTDIR should be the absolute or relative path to out directory
###GENOMEFASTA should be the absolute or relative path to the full genome faster files
###ANNOTFILE should be the absolute or relative path to the gff annotation file or gtf annotation file
###Remove --sjdbGTFtagExonParentTranscript command if gtf file given to ANNOTFILE variable. 

module use /depot/jwisecav/apps/modulefiles 
module load star    

echo 'module use /depot/jwisecav/apps/modulefiles'
echo 'module load star'
echo 'OUTDIR =' $OUTDIR
echo 'GENOMEFASTA =' $GENOMEFASTA
echo 'ANNOTFILE =' $ANNOTFILE  

echo 'STAR --runMode genomeGenerate --sjdbGTFtagExonParentTranscript Parent --genomeDir $OUTDIR --genomeFastaFiles $GENOMEFASTA --sjdbGTFfile $ANNOTFILE'

STAR --runMode genomeGenerate --sjdbGTFtagExonParentTranscript Parent --genomeDir $OUTDIR --genomeFastaFiles $GENOMEFASTA --sjdbGTFfile $ANNOTFILE 

