#!/bin/bash
#SBATCH --job-name=STAR_no_gene_map
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --mem=90G
#SBATCH --ntasks=45
#SBATCH --time=24:00:00     
#SBATCH --output=../slurm-out/%x.o%j
#SBATCH --error=../slurm-out/%x.e%j

##USAGE: export SAMPLE='sampleid'; export GENOMEDIR='/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/03_rnaseq_analysis/06_no_gene_map_STAR/STAR_index'; export SAMPLEDIR='/depot/jwisecav/data/ceratopteris/bsa_by_rnaseq/03_rnaseq_analysis/02_cleanRNAseq'; sbatch --mail-user=$EMAIL /depot/jwisecav/data/ceratopteris/github/ceratopteris_bsa_by_rnaseq/rnaseq_analysis/7_run_no_gene_map_STAR_2.sub

echo 'SAMPLE = ' $SAMPLE
echo 'GENOMEDIR = ' $GENOMEDIR
echo 'SAMPLEDIR = ' $SAMPLEDIR 

echo 'mkdir $SAMPLE'
mkdir $SAMPLE 

echo 'cd $SAMPLE' 
cd $SAMPLE

echo 'module use /depot/jwisecav/apps/modulefiles'
echo 'module load star'
module use /depot/jwisecav/apps/modulefiles
module load star

echo 'STAR --runThreadN 24 --genomeDir $GENOMEDIR --readFilesIn ${SAMPLEDIR}/${SAMPLE}_1.fq.gz ${SAMPLEDIR}/${SAMPLE}_2.fq.gz --readFilesCommand gunzip -c --outSAMtype BAM SortedByCoordinate --outBAMsortingThreadN 1'
STAR --runThreadN 24 --genomeDir $GENOMEDIR --readFilesIn ${SAMPLEDIR}/${SAMPLE}_1.fq.gz ${SAMPLEDIR}/${SAMPLE}_2.fq.gz --readFilesCommand gunzip -c --outSAMtype BAM SortedByCoordinate --outBAMsortingThreadN 1