#!/bin/bash
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=24:00:00     
#SBATCH --output=slurm-out/%x.o%j
#SBATCH --error=slurm-out/%x.e%j

# usage: export SRRID='SRRID'; export SAMPLE='sampleid'; sbatch --mail-user=$EMAIL -J "${SRRID}-sradump" /depot/jwisecav/data/ceratopteris/github/ceratopteris_bsa_by_rnaseq/rnaseq_analysis/run_sradump_paired.sub

module use /depot/jwisecav/apps/modulefiles/
module load sra-toolkit
module load fastqc

#User defined parameters
#INDIR="atallah_et_al_2018"
INDIR="marchant_et_al_2022"
OPTIONS='--split-spot --split-3 --temp /tmp --details --force --skip-technical'

cd $INDIR

echo fasterq-dump $OPTIONS $SRRID
fasterq-dump $OPTIONS $SRRID

gzip -f ${SRRID}_1.fastq
gzip -f ${SRRID}_2.fastq

ln -s -f ${SRRID}_1.fastq.gz ${SAMPLE}_1.fq.gz
ln -s -f ${SRRID}_2.fastq.gz ${SAMPLE}_2.fq.gz

echo fastqc ${SAMPLE}_1.fq.gz ${SAMPLE}_2.fq.gz
fastqc ${SAMPLE}_1.fq.gz ${SAMPLE}_2.fq.gz
