#!/bin/bash
#SBATCH --job-name=roughtree
#SBATCH --account=jwisecav
#SBATCH --mail-type=END,FAIL
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --time=12:00:00     
#SBATCH --output=%x.o%j
#SBATCH --error=%x.e%j

# usage: export OG='HER7'; sbatch --mail-user=$EMAIL ../scripts/run_roughtree.sub

CWD=$PWD

module load mafft

mafft --retree 0 --treeout --reorder --globalpair --weighti 0 --gop -2.0 --gep 0.1 --gexp -0.1 --averagelinkage ${OG}.fa > ${OG}.prune.fa